build:
  #!/usr/bin/env bash
  docker build . -t dbkegley/rsc-sample-content:custom-image

push:
  #!/usr/bin/env bash
  docker push dbkegley/rsc-sample-content:custom-image

bash:
  #!/usr/bin/env bash
  docker run --rm -it dbkegley/rsc-sample-content:custom-image /bin/bash
